# Generated by Django 5.0.2 on 2024-03-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='status',
            field=models.CharField(choices=[('start', 'start'), ('In Progress', 'In Progress'), ('Complate', 'complate')], max_length=100),
        ),
    ]
